class StateNames:
    def __init__(self):
        self.pp = ""    
    def fullName(self, abbrv):
        if abbrv == "AL": return "Alabama"
        if abbrv == "AK": return "Alaska"
        if abbrv == "AZ": return "Arizona"
        if abbrv == "AR": return "Arkansas"
        if abbrv == "CA": return "California"
        if abbrv == "CO": return "Colorado"
        if abbrv == "CT": return "Conneticut"
        if abbrv == "DE": return "Delaware"
        if abbrv == "FL": return "Florida"
        if abbrv == "GA": return "Georgia"
        if abbrv == "HI": return "Hawaii"
        if abbrv == "ID": return "Idaho"
        if abbrv == "IL": return "Illinois"
        if abbrv == "IN": return "Indiana"
        if abbrv == "IA": return "Iowa"
        if abbrv == "KS": return "Kansas"
        if abbrv == "KY": return "Kentucky"
        if abbrv == "LA": return "Louisiana"
        if abbrv == "ME": return "Maine"
        if abbrv == "MD": return "Maryland"
        if abbrv == "MA": return "Massachusetts"
        if abbrv == "MI": return "Michigan"
        if abbrv == "MN": return "Minnesota"
        if abbrv == "MS": return "Mississippi"
        if abbrv == "MO": return "Missouri"
        if abbrv == "MT": return "Montana"
        if abbrv == "NE": return "Nebraska"
        if abbrv == "NV": return "Nevada"
        if abbrv == "NH": return "New Hampshire"
        if abbrv == "NJ": return "New Jersey"
        if abbrv == "NM": return "New Mexico"
        if abbrv == "NY": return "New York"
        if abbrv == "NC": return "North Carolina"
        if abbrv == "ND": return "North Dakota"
        if abbrv == "OH": return "Ohio"
        if abbrv == "OK": return "Oklahoma"
        if abbrv == "OR": return "Oregon"
        if abbrv == "PA": return "Pennsylvania"
        if abbrv == "RI": return "Rhode Island"
        if abbrv == "SC": return "South Carolina"
        if abbrv == "SD": return "South Dakota"
        if abbrv == "TN": return "Tennessee"
        if abbrv == "TX": return "Texas"
        if abbrv == "UT": return "Utah"
        if abbrv == "VT": return "Vermont"
        if abbrv == "VA": return "Virginia"
        if abbrv == "WA": return "Washington"
        if abbrv == "WV": return "West Virginia"
        if abbrv == "WI": return "Wisconsin"
        if abbrv == "WY": return "Wyoming"
        else:
            return "pp"